id = "glass"
name = "Glass"
version = "0.1.0"
schema_version = 1
authors = ["Glass Contributors"]
description = "Glass language support"

[language_servers.glass]
name = "Glass Language Server"
languages = ["Glass"]

[grammars.glass]
repository = "file:///Users/tochkamac/projects/own/glass/tree-sitter-glass"
rev = "4a8d0ef5605fee00dd67c98fbfc0edcb87c5288e"
