use std::collections::{HashMap, HashSet};

use crate::ast::*;
use crate::closures::LambdaInfo;
use crate::modules::ResolvedImport;
use crate::type_repr::{Substitution, Type, TypeVarId};
use crate::types::TypeRegistry;

pub struct LuaCodegen {
    output: String,
    indent: usize,
    lambda_counter: usize,
    types: TypeRegistry,
    type_map: HashMap<(usize, usize), Type>,
    externals: HashMap<String, ExternalInfo>,
    mono_needed: HashSet<String>,
    type_param_vars: HashMap<String, HashMap<String, TypeVarId>>,
    mono_subst: Substitution,
    mono_param_types: HashMap<String, Type>,
    mono_generated: HashSet<String>,
    fn_defs: HashMap<String, FnDef>,
    const_values: HashMap<String, String>,
}

#[derive(Clone)]
struct ExternalInfo {
    lua_name: String,
    module: String,
}

impl LuaCodegen {
    pub fn new(
        types: TypeRegistry,
        _lambdas: Vec<LambdaInfo>,
        type_map: HashMap<(usize, usize), Type>,
        type_param_vars: HashMap<String, HashMap<String, TypeVarId>>,
    ) -> Self {
        Self {
            output: String::new(),
            indent: 0,
            lambda_counter: 0,
            types,
            type_map,
            externals: HashMap::new(),
            mono_needed: HashSet::new(),
            type_param_vars,
            mono_subst: Substitution::new(),
            mono_param_types: HashMap::new(),
            mono_generated: HashSet::new(),
            fn_defs: HashMap::new(),
            const_values: HashMap::new(),
        }
    }

    fn emit(&mut self, s: &str) {
        for _ in 0..self.indent {
            self.output.push_str("    ");
        }
        self.output.push_str(s);
        self.output.push('\n');
    }

    pub fn generate(mut self, module: &Module, imports: &[ResolvedImport]) -> String {
        // Phase 0: Collect external bindings and identify mono-needed functions
        for def in &module.definitions {
            match def {
                Definition::Const(c) => {
                    let value = self.gen_expr(&c.value.node);
                    self.const_values.insert(c.name.clone(), value);
                }
                Definition::External(e) => {
                    let info = ExternalInfo {
                        lua_name: e.name_in_module.clone(),
                        module: e.module.clone(),
                    };
                    self.externals.entry(e.fn_name.clone()).or_insert(info);
                }
                Definition::Function(f) => {
                    self.fn_defs.insert(f.name.clone(), f.clone());
                }
                _ => {}
            }
        }
        // Register qualified names for imported externals
        for imp in imports {
            if imp.qualified {
                for def in &imp.definitions {
                    if let Definition::External(e) = def {
                        let qualified = format!("{}.{}", imp.module_name, e.fn_name);
                        self.externals.insert(
                            qualified,
                            ExternalInfo {
                                lua_name: e.name_in_module.clone(),
                                module: e.module.clone(),
                            },
                        );
                    }
                }
            }
        }
        // Mark functions that call intrinsics as needing monomorphization
        let intrinsic_names: HashSet<String> = self
            .externals
            .iter()
            .filter(|(_, ext)| ext.module == "glass")
            .map(|(name, _)| name.clone())
            .collect();
        for (name, fdef) in &self.fn_defs {
            if Self::contains_intrinsic_call(&fdef.body.node, &intrinsic_names) {
                self.mono_needed.insert(name.clone());
            }
        }

        self.emit("-- Generated by Glass compiler (Lua target)");
        self.emit("");

        // Phase 1: Emit tag constants for enum types
        self.gen_tag_constants();

        // Phase 2: Emit user definitions (DCE + topologically sorted)
        let imported_count: usize = imports.iter().map(|i| i.definitions.len()).sum();
        let live_defs = dead_code_eliminate(&module.definitions, imported_count);
        let sorted_defs = topo_sort_definitions(&live_defs);
        for def in &sorted_defs {
            self.gen_definition(def);
            self.output.push('\n');
        }

        // Phase 3: Emit Elm runtime if applicable
        let elm_entry = crate::runtime::ElmEntryPoints::detect(module, &self.types);
        if let Some(entry) = elm_entry {
            crate::lua_runtime::gen_lua_elm_runtime(&entry, &mut self.output);
        }

        self.output
    }

    fn gen_tag_constants(&mut self) {
        let mut any = false;
        // Collect to avoid borrow issues
        struct EnumTagInfo {
            variants: Vec<(String, i64)>,
        }
        let type_infos: Vec<EnumTagInfo> = self
            .types
            .types
            .values()
            .filter(|info| info.is_enum)
            .map(|info| EnumTagInfo {
                variants: info
                    .variants
                    .iter()
                    .map(|v| (v.name.clone(), v.tag))
                    .collect(),
            })
            .collect();

        for info in &type_infos {
            for (vname, tag) in &info.variants {
                self.emit(&format!("local glass_TAG_{} = {}", vname, tag));
                any = true;
            }
        }
        if any {
            self.output.push('\n');
        }
    }

    // === Definitions ===

    fn gen_definition(&mut self, def: &Definition) {
        match def {
            Definition::Function(f) => self.gen_fn_def(f),
            Definition::Const(c) => self.gen_const_def(c),
            Definition::External(_)
            | Definition::Type(_)
            | Definition::Import(_)
            | Definition::Extend(_) => {}
        }
    }

    fn gen_fn_def(&mut self, f: &FnDef) {
        let params: Vec<String> = f
            .params
            .iter()
            .map(|p| {
                if p.name == "_" {
                    "_".to_string()
                } else {
                    p.name.clone()
                }
            })
            .collect();

        self.emit(&format!("function glass_{}({})", f.name, params.join(", ")));
        self.indent += 1;

        if let Expr::TcoLoop { body } = &f.body.node {
            // Lua has native TCO: emit body with `return f(...)` for tail calls
            self.gen_tco_body(&body.node, &f.name);
        } else {
            let result = self.gen_expr(&f.body.node);
            if f.return_type.is_some() {
                self.emit(&format!("return {}", result));
            }
        }

        self.indent -= 1;
        self.emit("end");
    }

    /// Generate expression in tail position for TCO.
    /// Lua has native TCO: emit `return f(...)` for tail calls.
    fn gen_tco_body(&mut self, expr: &Expr, fn_name: &str) {
        match expr {
            Expr::TcoContinue { args } => {
                // Emit proper tail call: return glass_fn(new_args)
                let arg_strs: Vec<String> = args
                    .iter()
                    .map(|(_, value)| self.gen_expr(&value.node))
                    .collect();
                self.emit(&format!(
                    "return glass_{}({})",
                    fn_name,
                    arg_strs.join(", ")
                ));
            }
            Expr::Case { subject, arms } => {
                let subj = self.gen_expr(&subject.node);
                let subj_var = format!("__case_{}", self.indent);
                self.emit(&format!("local {} = {}", subj_var, subj));

                for (i, arm) in arms.iter().enumerate() {
                    let condition = self.gen_pattern_condition(&arm.pattern.node, &subj_var);
                    let guard = arm
                        .guard
                        .as_ref()
                        .map(|g| format!(" and ({})", self.gen_expr(&g.node)))
                        .unwrap_or_default();

                    if i == 0 {
                        self.emit(&format!("if {}{} then", condition, guard));
                    } else if condition == "true" {
                        self.emit("else");
                    } else {
                        self.emit(&format!("elseif {}{} then", condition, guard));
                    }

                    self.indent += 1;
                    self.gen_pattern_bindings(&arm.pattern.node, &subj_var);
                    self.gen_tco_body(&arm.body.node, fn_name);
                    self.indent -= 1;
                }
                self.emit("end");
            }
            Expr::Let {
                pattern,
                value,
                body,
                ..
            } => {
                let val = self.gen_expr(&value.node);
                if let Pattern::Var(name) = &pattern.node {
                    self.emit(&format!("local {} = {}", name, val));
                }
                self.gen_tco_body(&body.node, fn_name);
            }
            Expr::Block(exprs) => {
                for (i, e) in exprs.iter().enumerate() {
                    if i < exprs.len() - 1 {
                        self.gen_expr(&e.node);
                    } else {
                        self.gen_tco_body(&e.node, fn_name);
                    }
                }
            }
            _ => {
                // Non-tail expression — evaluate and return
                let val = self.gen_expr(expr);
                self.emit(&format!("return {}", val));
            }
        }
    }

    fn gen_const_def(&mut self, _c: &ConstDef) {
        // Constants are fully inlined at use sites — no codegen needed.
    }

    // === Expressions ===

    #[allow(clippy::indexing_slicing)]
    fn gen_expr(&mut self, expr: &Expr) -> String {
        match expr {
            Expr::Int(n) => n.to_string(),
            Expr::Float(n) => format!("{:.1}", n),
            Expr::String(s) => format!("\"{}\"", s),
            Expr::Rawcode(s) => format!("FourCC(\"{}\")", s),
            Expr::Bool(b) => {
                if *b {
                    "true".to_string()
                } else {
                    "false".to_string()
                }
            }
            Expr::Var(name) => {
                if let Some(value) = self.const_values.get(name.as_str()) {
                    return value.clone();
                }
                name.clone()
            }

            Expr::BinOp { op, left, right } => {
                if let Some(result) = const_fold_binop(op, &left.node, &right.node) {
                    return result;
                }
                let l = self.gen_expr(&left.node);
                let r = self.gen_expr(&right.node);
                let op_str = match op {
                    BinOp::Add => "+",
                    BinOp::Sub => "-",
                    BinOp::Mul => "*",
                    BinOp::Div => "/",
                    BinOp::Mod => "%",
                    BinOp::Eq => "==",
                    BinOp::NotEq => "~=",
                    BinOp::Less => "<",
                    BinOp::Greater => ">",
                    BinOp::LessEq => "<=",
                    BinOp::GreaterEq => ">=",
                    BinOp::And => "and",
                    BinOp::Or => "or",
                    BinOp::StringConcat => "..",
                };
                format!("({} {} {})", l, op_str, r)
            }

            Expr::UnaryOp { op, operand } => {
                let o = self.gen_expr(&operand.node);
                match op {
                    UnaryOp::Negate => format!("-({})", o),
                    UnaryOp::Not => format!("not ({})", o),
                }
            }

            Expr::Call { function, args } => {
                // Check for external/intrinsic
                let ext_info = if let Expr::Var(name) = &function.node {
                    self.externals.get(name.as_str()).cloned()
                } else {
                    None
                };

                if let Some(ext) = ext_info {
                    let args_str: Vec<String> =
                        args.iter().map(|a| self.gen_expr(&a.node)).collect();
                    if ext.module == "glass" {
                        let call_span = Some(function.span);
                        return self.gen_intrinsic_call(&ext.lua_name, args, &args_str, call_span);
                    }
                    return format!("{}({})", ext.lua_name, args_str.join(", "));
                }

                let func_name = match &function.node {
                    Expr::Var(name) => {
                        // Check if variable holds a closure (not a top-level function)
                        let is_known_function = self.fn_defs.contains_key(name.as_str())
                            || self.externals.contains_key(name.as_str());
                        let is_closure_var = !is_known_function
                            && self
                                .lookup_full_type(function.span)
                                .is_some_and(|ty| matches!(ty, Type::Fn(_, _)));

                        if is_closure_var {
                            // In Lua, closures are first-class — just call the variable
                            let args_str: Vec<String> =
                                args.iter().map(|a| self.gen_expr(&a.node)).collect();
                            return format!("{}({})", name, args_str.join(", "));
                        }

                        // Check if this function needs monomorphization
                        if self.mono_needed.contains(name.as_str()) {
                            let concrete_types: Vec<Type> = args
                                .iter()
                                .map(|a| self.lookup_full_type(a.span).unwrap_or(Type::int()))
                                .collect();
                            let mangled = Self::mangle_types(&concrete_types);
                            let mono_name = format!("glass_{}_{}", name, mangled);
                            if !self.mono_generated.contains(&mono_name) {
                                self.mono_generated.insert(mono_name.clone());
                                let subst = self.build_mono_subst(name, &concrete_types);
                                self.gen_mono_function(name, &mono_name, subst);
                            }
                            let args_str: Vec<String> =
                                args.iter().map(|a| self.gen_expr(&a.node)).collect();
                            return format!("{}({})", mono_name, args_str.join(", "));
                        }
                        format!("glass_{}", name)
                    }
                    _ => self.gen_expr(&function.node),
                };
                let args_str: Vec<String> = args.iter().map(|a| self.gen_expr(&a.node)).collect();
                format!("{}({})", func_name, args_str.join(", "))
            }

            Expr::FieldAccess { object, field } => {
                if let Some(value) = self.const_values.get(field.as_str()) {
                    return value.clone();
                }
                let obj = self.gen_expr(&object.node);
                format!("{}.{}", obj, field)
            }

            Expr::MethodCall {
                object,
                method,
                args,
            } => {
                // Check if this is a qualified module call
                if let Expr::Var(module_name) = &object.node {
                    let qualified_name = format!("{}.{}", module_name, method);
                    let ext_info = self
                        .externals
                        .get(&qualified_name)
                        .or_else(|| self.externals.get(method.as_str()))
                        .cloned();
                    if let Some(ext) = ext_info {
                        let args_str: Vec<String> =
                            args.iter().map(|a| self.gen_expr(&a.node)).collect();
                        if ext.module == "glass" {
                            return self.gen_intrinsic_call(
                                &ext.lua_name,
                                args,
                                &args_str,
                                Some(object.span),
                            );
                        }
                        return format!("{}({})", ext.lua_name, args_str.join(", "));
                    }

                    // Check monomorphization
                    if self.mono_needed.contains(method.as_str()) {
                        let concrete_types: Vec<Type> = args
                            .iter()
                            .map(|a| self.lookup_full_type(a.span).unwrap_or(Type::int()))
                            .collect();
                        let mangled = Self::mangle_types(&concrete_types);
                        let mono_name = format!("glass_{}_{}", method, mangled);
                        if !self.mono_generated.contains(&mono_name) {
                            self.mono_generated.insert(mono_name.clone());
                            let subst = self.build_mono_subst(method, &concrete_types);
                            self.gen_mono_function(method, &mono_name, subst);
                        }
                        let args_str: Vec<String> =
                            args.iter().map(|a| self.gen_expr(&a.node)).collect();
                        return format!("{}({})", mono_name, args_str.join(", "));
                    }

                    let args_str: Vec<String> =
                        args.iter().map(|a| self.gen_expr(&a.node)).collect();
                    return format!("glass_{}({})", method, args_str.join(", "));
                }

                let obj = self.gen_expr(&object.node);
                let mut all_args = vec![obj];
                for a in args {
                    all_args.push(self.gen_expr(&a.node));
                }
                format!("glass_{}({})", method, all_args.join(", "))
            }

            Expr::Let {
                value,
                body,
                pattern,
                ..
            } => {
                let val = self.gen_expr(&value.node);
                self.gen_let_pattern_binding(&pattern.node, &val, &value.node);
                self.gen_expr(&body.node)
            }

            Expr::Case { subject, arms } => {
                let subj = self.gen_expr(&subject.node);

                // Use a local var to avoid re-evaluating subject
                let subj_var = format!("__case_{}", self.indent);
                self.emit(&format!("local {} = {}", subj_var, subj));

                // Use a result variable
                let result_var = format!("__result_{}", self.indent);
                self.emit(&format!("local {}", result_var));

                for (i, arm) in arms.iter().enumerate() {
                    let condition = self.gen_pattern_condition(&arm.pattern.node, &subj_var);
                    let guard = arm
                        .guard
                        .as_ref()
                        .map(|g| format!(" and ({})", self.gen_expr(&g.node)))
                        .unwrap_or_default();

                    if i == 0 {
                        self.emit(&format!("if {}{} then", condition, guard));
                    } else if condition == "true" {
                        self.emit("else");
                    } else {
                        self.emit(&format!("elseif {}{} then", condition, guard));
                    }

                    self.indent += 1;
                    self.gen_pattern_bindings(&arm.pattern.node, &subj_var);
                    let val = self.gen_expr(&arm.body.node);
                    self.emit(&format!("{} = {}", result_var, val));
                    self.indent -= 1;
                }
                self.emit("end");
                result_var
            }

            Expr::Block(exprs) => {
                let mut last = String::from("nil");
                for expr in exprs {
                    last = self.gen_expr(&expr.node);
                }
                last
            }

            Expr::Tuple(elems) => {
                let args: Vec<String> = elems.iter().map(|e| self.gen_expr(&e.node)).collect();
                format!("{{{}}}", args.join(", "))
            }

            Expr::List(elems) => {
                if elems.is_empty() {
                    "nil".to_string()
                } else {
                    // Build linked list right-to-left using tables
                    let mut result = "nil".to_string();
                    for elem in elems.iter().rev() {
                        let val = self.gen_expr(&elem.node);
                        result = format!("{{head = {}, tail = {}}}", val, result);
                    }
                    result
                }
            }

            Expr::ListCons { head, tail } => {
                let h = self.gen_expr(&head.node);
                let t = self.gen_expr(&tail.node);
                format!("{{head = {}, tail = {}}}", h, t)
            }

            Expr::Pipe { left, right } => {
                let l = self.gen_expr(&left.node);
                match &right.node {
                    Expr::Call { function, args } => {
                        let func_name = match &function.node {
                            Expr::Var(name) => {
                                if self.externals.contains_key(name.as_str()) {
                                    self.externals[name.as_str()].lua_name.clone()
                                } else {
                                    format!("glass_{}", name)
                                }
                            }
                            _ => self.gen_expr(&function.node),
                        };
                        let has_placeholder = args
                            .iter()
                            .any(|a| matches!(&a.node, Expr::Var(n) if n == "_"));
                        let all_args: Vec<String> = if has_placeholder {
                            args.iter()
                                .map(|a| {
                                    if matches!(&a.node, Expr::Var(n) if n == "_") {
                                        l.clone()
                                    } else {
                                        self.gen_expr(&a.node)
                                    }
                                })
                                .collect()
                        } else {
                            let mut all = vec![l];
                            for a in args {
                                all.push(self.gen_expr(&a.node));
                            }
                            all
                        };
                        format!("{}({})", func_name, all_args.join(", "))
                    }
                    Expr::Var(name) => {
                        if self.externals.contains_key(name.as_str()) {
                            format!("{}({})", self.externals[name.as_str()].lua_name, l)
                        } else {
                            format!("glass_{}({})", name, l)
                        }
                    }
                    // x |> module.func → glass_func(x)
                    // x |> module.func(a, _) → glass_func(a, x)
                    Expr::MethodCall {
                        object,
                        method,
                        args,
                    } => {
                        let ext_info = if let Expr::Var(module_name) = &object.node {
                            let qualified = format!("{}.{}", module_name, method);
                            self.externals
                                .get(&qualified)
                                .or_else(|| self.externals.get(method.as_str()))
                                .cloned()
                        } else {
                            None
                        };
                        let func_name = match &ext_info {
                            Some(ext) => ext.lua_name.clone(),
                            None => format!("glass_{}", method),
                        };
                        if args.is_empty() {
                            format!("{}({})", func_name, l)
                        } else {
                            let has_placeholder = args
                                .iter()
                                .any(|a| matches!(&a.node, Expr::Var(n) if n == "_"));
                            let all_args: Vec<String> = if has_placeholder {
                                args.iter()
                                    .map(|a| {
                                        if matches!(&a.node, Expr::Var(n) if n == "_") {
                                            l.clone()
                                        } else {
                                            self.gen_expr(&a.node)
                                        }
                                    })
                                    .collect()
                            } else {
                                let mut all = vec![l];
                                for a in args {
                                    all.push(self.gen_expr(&a.node));
                                }
                                all
                            };
                            format!("{}({})", func_name, all_args.join(", "))
                        }
                    }
                    _ => {
                        let r = self.gen_expr(&right.node);
                        format!("{}({})", r, l)
                    }
                }
            }

            Expr::Constructor { name, args } => {
                if args.is_empty()
                    && !name.contains("::")
                    && let Some(value) = self.const_values.get(name.as_str())
                {
                    return value.clone();
                }
                let bare_name = name.rsplit("::").next().unwrap_or(name);
                let variant_info = self.types.get_variant(bare_name).map(|(ti, vi)| {
                    (
                        ti.name.clone(),
                        ti.is_enum,
                        vi.name.clone(),
                        vi.tag,
                        vi.fields.iter().map(|f| f.name.clone()).collect::<Vec<_>>(),
                    )
                });

                match variant_info {
                    Some((_type_name, is_enum, vname, _tag, field_names)) => {
                        let mut fields = Vec::new();
                        if is_enum {
                            fields.push(format!("tag = glass_TAG_{}", vname));
                        }
                        for (i, a) in args.iter().enumerate() {
                            let e = match a {
                                ConstructorArg::Positional(e) | ConstructorArg::Named(_, e) => e,
                            };
                            let val = self.gen_expr(&e.node);
                            let fname = match a {
                                ConstructorArg::Named(n, _) => n.clone(),
                                ConstructorArg::Positional(_) => field_names
                                    .get(i)
                                    .cloned()
                                    .unwrap_or_else(|| format!("_{}", i)),
                            };
                            fields.push(format!("{} = {}", fname, val));
                        }
                        if fields.is_empty() {
                            if is_enum {
                                // Nullary enum variant — just the tag constant
                                format!("glass_TAG_{}", vname)
                            } else {
                                "{}".to_string()
                            }
                        } else {
                            format!("{{{}}}", fields.join(", "))
                        }
                    }
                    None => {
                        format!("nil --[[ unknown constructor {} ]]", name)
                    }
                }
            }

            Expr::RecordUpdate {
                name,
                base,
                updates,
            } => {
                let record_info: Option<Vec<String>> =
                    self.types.types.get(name.as_str()).and_then(|info| {
                        if info.is_enum {
                            return None;
                        }
                        let v = info.variants.first()?;
                        Some(v.fields.iter().map(|f| f.name.clone()).collect())
                    });

                match record_info {
                    Some(field_names) => {
                        let base_val = self.gen_expr(&base.node);
                        let base_var = format!("__base_{}", self.indent);
                        self.emit(&format!("local {} = {}", base_var, base_val));
                        let mut fields = Vec::new();
                        for fname in &field_names {
                            let updated = updates.iter().find(|(n, _)| n == fname);
                            match updated {
                                Some((_, val)) => {
                                    let v = self.gen_expr(&val.node);
                                    fields.push(format!("{} = {}", fname, v));
                                }
                                None => {
                                    fields.push(format!("{} = {}.{}", fname, base_var, fname));
                                }
                            }
                        }
                        format!("{{{}}}", fields.join(", "))
                    }
                    None => {
                        format!("nil --[[ TODO: update {} ]]", name)
                    }
                }
            }

            Expr::Lambda { params, body, .. } => {
                // In Lua, lambdas are native closures
                self.lambda_counter += 1;
                let param_names: Vec<String> = params
                    .iter()
                    .map(|p| {
                        if p.name == "_" {
                            "_".to_string()
                        } else {
                            p.name.clone()
                        }
                    })
                    .collect();
                let saved_indent = self.indent;
                self.indent += 1;
                let result = self.gen_expr(&body.node);
                self.indent = saved_indent;
                // For simple expressions, use inline form
                format!("function({}) return {} end", param_names.join(", "), result)
            }

            Expr::Clone(inner) => self.gen_expr(&inner.node),

            Expr::Todo(msg) => {
                let msg_str = msg
                    .as_ref()
                    .map(|s| format!("\"{}\"", s))
                    .unwrap_or_else(|| "\"todo\"".to_string());
                format!("error({})", msg_str)
            }

            // TCO nodes handled by gen_tco_body
            Expr::TcoLoop { .. } | Expr::TcoContinue { .. } => "0".to_string(),
        }
    }

    // === Pattern matching ===

    fn gen_pattern_condition(&self, pattern: &Pattern, subject: &str) -> String {
        match pattern {
            Pattern::Bool(true) => format!("({} == true)", subject),
            Pattern::Bool(false) => format!("({} == false)", subject),
            Pattern::Int(n) => format!("({} == {})", subject, n),
            Pattern::Rawcode(s) => format!("({} == FourCC(\"{}\"))", subject, s),
            Pattern::String(s) => format!("({} == \"{}\")", subject, s),
            Pattern::Constructor { name, args } => {
                let bare = bare_ctor_name(name);
                if args.is_empty() {
                    let const_key = bare.rsplit('.').next().unwrap_or(bare);
                    if let Some(value) = self.const_values.get(const_key) {
                        format!("({} == {})", subject, value)
                    } else {
                        format!("({} == glass_TAG_{})", subject, bare)
                    }
                } else {
                    format!("({}.tag == glass_TAG_{})", subject, bare)
                }
            }
            Pattern::ConstructorNamed { name, .. } => {
                let bare = bare_ctor_name(name);
                format!("({}.tag == glass_TAG_{})", subject, bare)
            }
            Pattern::Or(alternatives) => {
                let conditions: Vec<String> = alternatives
                    .iter()
                    .map(|alt| self.gen_pattern_condition(&alt.node, subject))
                    .collect();
                format!("({})", conditions.join(" or "))
            }
            Pattern::As { pattern, .. } => self.gen_pattern_condition(&pattern.node, subject),
            Pattern::List(elems) if elems.is_empty() => {
                format!("({} == nil)", subject)
            }
            Pattern::ListCons { .. } => {
                format!("({} ~= nil)", subject)
            }
            _ => "true".to_string(),
        }
    }

    fn gen_let_pattern_binding(&mut self, pattern: &Pattern, val: &str, value_expr: &Expr) {
        match pattern {
            Pattern::Var(name) => {
                self.emit(&format!("local {} = {}", name, val));
            }
            Pattern::Discard => {
                // Only emit bare call expressions for side effects.
                // Check the val string: only emit if the original expression is a call
                // AND we're not inside a tuple destructure (val would be a field access).
                if matches!(value_expr, Expr::Call { .. }) && !val.contains('[') {
                    self.emit(val);
                }
            }
            Pattern::Tuple(elems) => {
                let tmp = format!("__tup_{}", self.indent);
                self.emit(&format!("local {} = {}", tmp, val));
                for (i, elem) in elems.iter().enumerate() {
                    let field_val = format!("{}[{}]", tmp, i + 1);
                    self.gen_let_pattern_binding(&elem.node, &field_val, value_expr);
                }
            }
            Pattern::Constructor { args, .. } => {
                for (i, arg) in args.iter().enumerate() {
                    let field = format!("{}[{}]", val, i + 1);
                    self.gen_let_pattern_binding(&arg.node, &field, value_expr);
                }
            }
            _ => {
                // Ignore unknown patterns
            }
        }
    }

    fn gen_pattern_bindings(&mut self, pattern: &Pattern, subject: &str) {
        match pattern {
            Pattern::Var(name) => {
                self.emit(&format!("local {} = {}", name, subject));
            }
            Pattern::Constructor { name, args } => {
                let bare = bare_ctor_name(name);
                let field_names: Vec<String> = self
                    .types
                    .get_variant(bare)
                    .map(|(_, v)| v.fields.iter().map(|f| f.name.clone()).collect())
                    .unwrap_or_default();
                for (i, arg) in args.iter().enumerate() {
                    let fname = field_names
                        .get(i)
                        .cloned()
                        .unwrap_or_else(|| format!("_{}", i));
                    let field = format!("{}.{}", subject, fname);
                    self.gen_pattern_bindings(&arg.node, &field);
                }
            }
            Pattern::ConstructorNamed { name, fields, .. } => {
                let _ = name;
                for fp in fields {
                    let var = fp.binding.as_ref().unwrap_or(&fp.field_name);
                    let field = format!("{}.{}", subject, fp.field_name);
                    self.emit(&format!("local {} = {}", var, field));
                }
            }
            Pattern::Or(alternatives) => {
                if let Some(first) = alternatives.first() {
                    self.gen_pattern_bindings(&first.node, subject);
                }
            }
            Pattern::ListCons { head, tail } => {
                let head_expr = format!("{}.head", subject);
                let tail_expr = format!("{}.tail", subject);
                self.gen_pattern_bindings(&head.node, &head_expr);
                self.gen_pattern_bindings(&tail.node, &tail_expr);
            }
            Pattern::Tuple(elems) => {
                for (i, elem) in elems.iter().enumerate() {
                    let field = format!("{}[{}]", subject, i + 1);
                    self.gen_pattern_bindings(&elem.node, &field);
                }
            }
            Pattern::As { pattern, name } => {
                self.emit(&format!("local {} = {}", name, subject));
                self.gen_pattern_bindings(&pattern.node, subject);
            }
            _ => {}
        }
    }

    // === Intrinsics ===

    fn gen_intrinsic_call(
        &self,
        intrinsic: &str,
        args: &[Spanned<Expr>],
        args_str: &[String],
        call_span: Option<crate::token::Span>,
    ) -> String {
        match intrinsic {
            "dict_save" => {
                // Type-directed: 4th arg (value) determines which Save* native
                let value_type = args
                    .get(3)
                    .map(|a| self.resolve_arg_type(a))
                    .unwrap_or("integer");
                let lua_fn = match value_type {
                    "real" => "SaveReal",
                    "string" => "SaveStr",
                    "boolean" => "SaveBoolean",
                    _ => "SaveInteger",
                };
                format!("{}({})", lua_fn, args_str.join(", "))
            }
            "dict_load" => {
                // Return type determines which Load* native
                let ret_type = call_span
                    .and_then(|s| self.type_map.get(&(s.start, s.end)))
                    .and_then(|ty| match ty {
                        Type::Fn(_, ret) => Some(ret.to_jass()),
                        _ => None,
                    })
                    .unwrap_or("integer");
                let lua_fn = match ret_type {
                    "real" => "LoadReal",
                    "string" => "LoadStr",
                    "boolean" => "LoadBoolean",
                    _ => "LoadInteger",
                };
                format!("{}({})", lua_fn, args_str.join(", "))
            }
            "dict_has" => {
                let key_type = args
                    .get(2)
                    .map(|a| self.lookup_type(a.span))
                    .unwrap_or("integer");
                let lua_fn = match key_type {
                    "real" => "HaveSavedReal",
                    "string" => "HaveSavedString",
                    "boolean" => "HaveSavedBoolean",
                    _ => "HaveSavedInteger",
                };
                format!("{}({})", lua_fn, args_str.join(", "))
            }
            "dict_remove" => {
                let key_type = args
                    .get(2)
                    .map(|a| self.lookup_type(a.span))
                    .unwrap_or("integer");
                let lua_fn = match key_type {
                    "real" => "RemoveSavedReal",
                    "string" => "RemoveSavedString",
                    "boolean" => "RemoveSavedBoolean",
                    _ => "RemoveSavedInteger",
                };
                format!("{}({})", lua_fn, args_str.join(", "))
            }
            _ => {
                format!("glass_{}({})", intrinsic, args_str.join(", "))
            }
        }
    }

    // === Type lookup helpers ===

    /// Look up the resolved JASS type string for a spanned expression.
    fn lookup_type(&self, span: crate::token::Span) -> &'static str {
        if let Some(ty) = self.type_map.get(&(span.start, span.end)) {
            let resolved = ty.apply(&self.mono_subst);
            if !resolved.free_vars().is_empty() {
                return "integer";
            }
            resolved.to_jass()
        } else {
            "integer"
        }
    }

    /// Resolve the type of an argument expression, checking mono_param_types first.
    fn resolve_arg_type(&self, arg: &Spanned<Expr>) -> &'static str {
        if let Expr::Var(name) = &arg.node
            && let Some(ty) = self.mono_param_types.get(name.as_str())
        {
            return ty.to_jass();
        }
        self.lookup_type(arg.span)
    }

    fn lookup_full_type(&self, span: crate::token::Span) -> Option<Type> {
        self.type_map
            .get(&(span.start, span.end))
            .map(|ty| ty.apply(&self.mono_subst))
    }

    // === Monomorphization ===

    fn mangle_types(types: &[Type]) -> String {
        types
            .iter()
            .map(|t| t.to_jass().replace(' ', "_"))
            .collect::<Vec<_>>()
            .join("_")
    }

    fn build_mono_subst(&self, fn_name: &str, concrete_arg_types: &[Type]) -> Substitution {
        let mut subst = Substitution::new();
        if let Some(tvars) = self.type_param_vars.get(fn_name)
            && let Some(fdef) = self.fn_defs.get(fn_name)
        {
            let mut name_to_type: HashMap<String, Type> = HashMap::new();
            for (param, concrete) in fdef.params.iter().zip(concrete_arg_types.iter()) {
                Self::extract_type_bindings(&param.type_expr, concrete, &mut name_to_type);
            }
            for (name, var_id) in tvars {
                if let Some(concrete_type) = name_to_type.get(name) {
                    subst.0.insert(*var_id, concrete_type.clone());
                }
            }
        }
        subst
    }

    fn extract_type_bindings(
        type_expr: &TypeExpr,
        concrete: &Type,
        bindings: &mut HashMap<String, Type>,
    ) {
        match type_expr {
            TypeExpr::Named { name, args } => {
                if name.chars().next().is_some_and(|c| c.is_lowercase()) {
                    bindings.insert(name.clone(), concrete.clone());
                } else if let Type::App(_, concrete_args) = concrete {
                    for (te, ct) in args.iter().zip(concrete_args.iter()) {
                        Self::extract_type_bindings(te, ct, bindings);
                    }
                }
            }
            TypeExpr::Tuple(elems) => {
                if let Type::Tuple(concrete_elems) = concrete {
                    for (te, ct) in elems.iter().zip(concrete_elems.iter()) {
                        Self::extract_type_bindings(te, ct, bindings);
                    }
                }
            }
            TypeExpr::Fn { params, ret } => {
                if let Type::Fn(concrete_params, concrete_ret) = concrete {
                    for (te, ct) in params.iter().zip(concrete_params.iter()) {
                        Self::extract_type_bindings(te, ct, bindings);
                    }
                    Self::extract_type_bindings(ret, concrete_ret, bindings);
                }
            }
        }
    }

    fn gen_mono_function(&mut self, orig_name: &str, mono_name: &str, subst: Substitution) {
        let fdef = match self.fn_defs.get(orig_name).cloned() {
            Some(f) => f,
            None => return,
        };

        let prev_subst = std::mem::replace(&mut self.mono_subst, subst);
        let prev_param_types = std::mem::take(&mut self.mono_param_types);
        let prev_output = std::mem::take(&mut self.output);
        let prev_indent = std::mem::replace(&mut self.indent, 0);

        for p in &fdef.params {
            let concrete_type = self.resolve_type_expr_to_type(&p.type_expr);
            self.mono_param_types.insert(p.name.clone(), concrete_type);
        }

        let params: Vec<String> = fdef.params.iter().map(|p| p.name.clone()).collect();

        self.emit(&format!("function {}({})", mono_name, params.join(", ")));
        self.indent = 1;
        let result = self.gen_expr(&fdef.body.node);
        if fdef.return_type.is_some() {
            self.emit(&format!("return {}", result));
        }
        self.indent = 0;
        self.emit("end");

        let mono_output = std::mem::replace(&mut self.output, prev_output);
        self.indent = prev_indent;
        self.mono_subst = prev_subst;
        self.mono_param_types = prev_param_types;

        self.output = format!("{}\n{}", mono_output, self.output);
    }

    fn resolve_type_expr_to_type(&self, ty: &TypeExpr) -> Type {
        match ty {
            TypeExpr::Named { name, args } => {
                if name.chars().next().is_some_and(|c| c.is_lowercase()) {
                    for tvars in self.type_param_vars.values() {
                        if let Some(&var_id) = tvars.get(name.as_str())
                            && let Some(concrete) = self.mono_subst.0.get(&var_id)
                        {
                            return concrete.clone();
                        }
                    }
                    Type::Var(0)
                } else if args.is_empty() {
                    Type::Con(name.clone())
                } else {
                    let resolved_args: Vec<Type> = args
                        .iter()
                        .map(|a| self.resolve_type_expr_to_type(a))
                        .collect();
                    Type::App(Box::new(Type::Con(name.clone())), resolved_args)
                }
            }
            TypeExpr::Tuple(elems) => Type::Tuple(
                elems
                    .iter()
                    .map(|e| self.resolve_type_expr_to_type(e))
                    .collect(),
            ),
            TypeExpr::Fn { params, ret } => Type::Fn(
                params
                    .iter()
                    .map(|p| self.resolve_type_expr_to_type(p))
                    .collect(),
                Box::new(self.resolve_type_expr_to_type(ret)),
            ),
        }
    }

    fn contains_intrinsic_call(expr: &Expr, intrinsics: &HashSet<String>) -> bool {
        match expr {
            Expr::Call { function, args } => {
                if let Expr::Var(name) = &function.node
                    && intrinsics.contains(name)
                {
                    return true;
                }
                args.iter()
                    .any(|a| Self::contains_intrinsic_call(&a.node, intrinsics))
            }
            Expr::Let { value, body, .. } => {
                Self::contains_intrinsic_call(&value.node, intrinsics)
                    || Self::contains_intrinsic_call(&body.node, intrinsics)
            }
            Expr::Case { subject, arms } => {
                Self::contains_intrinsic_call(&subject.node, intrinsics)
                    || arms
                        .iter()
                        .any(|arm| Self::contains_intrinsic_call(&arm.body.node, intrinsics))
            }
            Expr::Block(exprs) => exprs
                .iter()
                .any(|e| Self::contains_intrinsic_call(&e.node, intrinsics)),
            _ => false,
        }
    }
}

fn bare_ctor_name(name: &str) -> &str {
    name.rsplit("::").next().unwrap_or(name)
}

/// Constant folding for Lua.
fn const_fold_binop(op: &BinOp, left: &Expr, right: &Expr) -> Option<String> {
    match (op, left, right) {
        (BinOp::Add, Expr::Int(a), Expr::Int(b)) => Some(format!("{}", a + b)),
        (BinOp::Sub, Expr::Int(a), Expr::Int(b)) => Some(format!("{}", a - b)),
        (BinOp::Mul, Expr::Int(a), Expr::Int(b)) => Some(format!("{}", a * b)),
        (BinOp::Div, Expr::Int(a), Expr::Int(b)) if *b != 0 => Some(format!("{}", a / b)),
        (BinOp::Mod, Expr::Int(a), Expr::Int(b)) if *b != 0 => Some(format!("{}", a % b)),
        (BinOp::Add, Expr::Float(a), Expr::Float(b)) => Some(format!("{:.1}", a + b)),
        (BinOp::Sub, Expr::Float(a), Expr::Float(b)) => Some(format!("{:.1}", a - b)),
        (BinOp::Mul, Expr::Float(a), Expr::Float(b)) => Some(format!("{:.1}", a * b)),
        (BinOp::StringConcat, Expr::String(a), Expr::String(b)) => Some(format!("\"{}{}\"", a, b)),
        (BinOp::Eq, Expr::Int(a), Expr::Int(b)) => {
            Some(if a == b { "true" } else { "false" }.into())
        }
        (BinOp::NotEq, Expr::Int(a), Expr::Int(b)) => {
            Some(if a == b { "false" } else { "true" }.into())
        }
        (BinOp::Less, Expr::Int(a), Expr::Int(b)) => {
            Some(if a < b { "true" } else { "false" }.into())
        }
        (BinOp::Greater, Expr::Int(a), Expr::Int(b)) => {
            Some(if a > b { "true" } else { "false" }.into())
        }
        _ => None,
    }
}

/// Dead code elimination (same logic as JASS codegen).
fn dead_code_eliminate(defs: &[Definition], imported_count: usize) -> Vec<Definition> {
    let mut fn_indices: HashMap<&str, usize> = HashMap::new();
    for (i, def) in defs.iter().enumerate() {
        match def {
            Definition::Function(f) => {
                fn_indices.insert(&f.name, i);
            }
            Definition::External(e) => {
                fn_indices.insert(&e.fn_name, i);
            }
            _ => {}
        }
    }

    let mut calls: HashMap<usize, HashSet<usize>> = HashMap::new();
    for (i, def) in defs.iter().enumerate() {
        if let Definition::Function(f) = def {
            let mut called = HashSet::new();
            collect_calls_in_expr(&f.body, &fn_indices, &mut called);
            calls.insert(i, called);
        }
    }

    let has_entry_points = defs.iter().any(|d| {
        matches!(d,
            Definition::Function(f) if f.is_pub || matches!(f.name.as_str(), "init" | "update" | "subscriptions")
        )
    });
    if !has_entry_points {
        return defs.to_vec();
    }

    let mut reachable: HashSet<usize> = HashSet::new();
    for (i, def) in defs.iter().enumerate() {
        let is_entry = match def {
            Definition::Type(_)
            | Definition::Import(_)
            | Definition::Extend(_)
            | Definition::Const(_)
            | Definition::External(_) => true,
            Definition::Function(f) => {
                let is_user_def = i >= imported_count;
                (is_user_def && f.is_pub)
                    || matches!(f.name.as_str(), "init" | "update" | "subscriptions")
            }
        };
        if is_entry {
            reachable.insert(i);
        }
    }

    let mut queue: Vec<usize> = reachable.iter().copied().collect();
    while let Some(idx) = queue.pop() {
        if let Some(callees) = calls.get(&idx) {
            for &callee in callees {
                if reachable.insert(callee) {
                    queue.push(callee);
                }
            }
        }
    }

    defs.iter()
        .enumerate()
        .filter(|(i, _)| reachable.contains(i))
        .map(|(_, d)| d.clone())
        .collect()
}

/// Topological sort for Lua (functions must be defined before use in Lua too).
fn topo_sort_definitions(defs: &[Definition]) -> Vec<&Definition> {
    let mut fn_indices: HashMap<&str, usize> = HashMap::new();
    for (i, def) in defs.iter().enumerate() {
        match def {
            Definition::Function(f) => {
                fn_indices.insert(&f.name, i);
            }
            Definition::External(e) => {
                fn_indices.insert(&e.fn_name, i);
            }
            _ => {}
        }
    }

    let mut deps: HashMap<usize, HashSet<usize>> = HashMap::new();
    for (i, def) in defs.iter().enumerate() {
        if let Definition::Function(f) = def {
            let mut called = HashSet::new();
            collect_calls_in_expr(&f.body, &fn_indices, &mut called);
            deps.insert(i, called);
        }
    }

    let n = defs.len();
    let mut in_deg = vec![0usize; n];
    for (&caller, callees) in &deps {
        if let Some(slot) = in_deg.get_mut(caller) {
            *slot = callees.len();
        }
    }

    let mut queue: Vec<usize> = (0..n)
        .filter(|&i| in_deg.get(i).copied() == Some(0))
        .collect();
    let mut sorted: Vec<usize> = Vec::new();

    let mut callers_of: HashMap<usize, Vec<usize>> = HashMap::new();
    for (&caller, callees) in &deps {
        for &callee in callees {
            callers_of.entry(callee).or_default().push(caller);
        }
    }

    while let Some(node) = queue.pop() {
        sorted.push(node);
        if let Some(callers) = callers_of.get(&node) {
            for &caller in callers {
                if let Some(deg) = in_deg.get_mut(caller) {
                    *deg -= 1;
                    if *deg == 0 {
                        queue.push(caller);
                    }
                }
            }
        }
    }

    let in_sorted: HashSet<usize> = sorted.iter().copied().collect();
    for i in 0..n {
        if !in_sorted.contains(&i) {
            sorted.push(i);
        }
    }

    sorted.iter().filter_map(|&i| defs.get(i)).collect()
}

fn collect_calls_in_expr(
    expr: &Spanned<Expr>,
    fn_map: &HashMap<&str, usize>,
    out: &mut HashSet<usize>,
) {
    match &expr.node {
        Expr::Call { function, args } => {
            if let Expr::Var(name) = &function.node
                && let Some(&idx) = fn_map.get(name.as_str())
            {
                out.insert(idx);
            }
            collect_calls_in_expr(function, fn_map, out);
            for a in args {
                collect_calls_in_expr(a, fn_map, out);
            }
        }
        Expr::Var(name) => {
            if let Some(&idx) = fn_map.get(name.as_str()) {
                out.insert(idx);
            }
        }
        Expr::Let { value, body, .. } => {
            collect_calls_in_expr(value, fn_map, out);
            collect_calls_in_expr(body, fn_map, out);
        }
        Expr::Case { subject, arms } => {
            collect_calls_in_expr(subject, fn_map, out);
            for arm in arms {
                collect_calls_in_expr(&arm.body, fn_map, out);
                if let Some(g) = &arm.guard {
                    collect_calls_in_expr(g, fn_map, out);
                }
            }
        }
        Expr::BinOp { left, right, .. } | Expr::Pipe { left, right } => {
            collect_calls_in_expr(left, fn_map, out);
            collect_calls_in_expr(right, fn_map, out);
        }
        Expr::UnaryOp { operand, .. } | Expr::Clone(operand) => {
            collect_calls_in_expr(operand, fn_map, out);
        }
        Expr::Block(exprs) => {
            for e in exprs {
                collect_calls_in_expr(e, fn_map, out);
            }
        }
        Expr::Tuple(elems) | Expr::List(elems) => {
            for e in elems {
                collect_calls_in_expr(e, fn_map, out);
            }
        }
        Expr::ListCons { head, tail } => {
            collect_calls_in_expr(head, fn_map, out);
            collect_calls_in_expr(tail, fn_map, out);
        }
        Expr::Lambda { body, .. } => collect_calls_in_expr(body, fn_map, out),
        Expr::MethodCall {
            object,
            method,
            args,
        } => {
            if let Some(&idx) = fn_map.get(method.as_str()) {
                out.insert(idx);
            }
            collect_calls_in_expr(object, fn_map, out);
            for a in args {
                collect_calls_in_expr(a, fn_map, out);
            }
        }
        Expr::FieldAccess { object, .. } => collect_calls_in_expr(object, fn_map, out),
        Expr::Constructor { args, .. } => {
            for a in args {
                let e = match a {
                    ConstructorArg::Positional(e) | ConstructorArg::Named(_, e) => e,
                };
                collect_calls_in_expr(e, fn_map, out);
            }
        }
        Expr::RecordUpdate { base, updates, .. } => {
            collect_calls_in_expr(base, fn_map, out);
            for (_, e) in updates {
                collect_calls_in_expr(e, fn_map, out);
            }
        }
        _ => {}
    }
}
